-- Test data for EntradasApp (extensive)
-- Users
INSERT INTO USUARIO (ID, NOMBRE, EMAIL, CONTRASENIA, EDAD, TELEFONO, ADMIN, SALDO) VALUES (1, 'Pedro', 'pedro@example.com', 'x', 30, '600000000', FALSE, 100.0);
INSERT INTO USUARIO (ID, NOMBRE, EMAIL, CONTRASENIA, EDAD, TELEFONO, ADMIN, SALDO) VALUES (2, 'Admin', 'admin@example.com', 'adminpass', 35, '600000001', TRUE, 1000.0);
INSERT INTO USUARIO (ID, NOMBRE, EMAIL, CONTRASENIA, EDAD, TELEFONO, ADMIN, SALDO) VALUES (3, 'Lucia', 'lucia@example.com', 'pass', 22, '600000002', FALSE, 25.0);
INSERT INTO USUARIO (ID, NOMBRE, EMAIL, CONTRASENIA, EDAD, TELEFONO, ADMIN, SALDO) VALUES (4, 'Carlos', 'carlos@example.com', 'pass', 17, '600000003', FALSE, 5.0);
INSERT INTO USUARIO (ID, NOMBRE, EMAIL, CONTRASENIA, EDAD, TELEFONO, ADMIN, SALDO) VALUES (5, 'Marta', 'marta@example.com', 'pass', 45, '600000004', FALSE, 200.0);
INSERT INTO USUARIO (ID, NOMBRE, EMAIL, CONTRASENIA, EDAD, TELEFONO, ADMIN, SALDO) VALUES (6, 'UsuarioA', 'usera@example.com', 'pass', 28, '600000100', FALSE, 50.0);
INSERT INTO USUARIO (ID, NOMBRE, EMAIL, CONTRASENIA, EDAD, TELEFONO, ADMIN, SALDO) VALUES (7, 'UsuarioB', 'userb@example.com', 'pass', 30, '600000101', FALSE, 50.0);

-- Ubicaciones
INSERT INTO UBICACION (ID, NOMBRE) VALUES (1, 'Centro');
INSERT INTO UBICACION (ID, NOMBRE) VALUES (2, 'Norte');
INSERT INTO UBICACION (ID, NOMBRE) VALUES (3, 'Sur');
INSERT INTO UBICACION (ID, NOMBRE) VALUES (4, 'Este');
INSERT INTO UBICACION (ID, NOMBRE) VALUES (5, 'Oeste');
INSERT INTO UBICACION (ID, NOMBRE) VALUES (6, 'Universitario');
INSERT INTO UBICACION (ID, NOMBRE) VALUES (7, 'Parque');
INSERT INTO UBICACION (ID, NOMBRE) VALUES (8, 'ZonaIndustrial');

-- Locales (diversos, asociados a ubicaciones)
INSERT INTO LOCAL (ID, NOMBRE, UBICACION_ID) VALUES (1, 'Sala Azul', 1);
INSERT INTO LOCAL (ID, NOMBRE, UBICACION_ID) VALUES (2, 'Teatro Norte', 2);
INSERT INTO LOCAL (ID, NOMBRE, UBICACION_ID) VALUES (3, 'Auditorio Central', 1);
INSERT INTO LOCAL (ID, NOMBRE, UBICACION_ID) VALUES (4, 'Sala Pequeña', 3);
INSERT INTO LOCAL (ID, NOMBRE, UBICACION_ID) VALUES (5, 'Estadio Oeste', 5);
INSERT INTO LOCAL (ID, NOMBRE, UBICACION_ID) VALUES (6, 'Cafeteria Uni', 6);
INSERT INTO LOCAL (ID, NOMBRE, UBICACION_ID) VALUES (7, 'Plaza del Parque', 7);
INSERT INTO LOCAL (ID, NOMBRE, UBICACION_ID) VALUES (8, 'Nave Industrial', 8);
INSERT INTO LOCAL (ID, NOMBRE, UBICACION_ID) VALUES (9, 'Sala VIP', 1);
INSERT INTO LOCAL (ID, NOMBRE, UBICACION_ID) VALUES (10, 'Teatro Sur', 3);

-- Eventos variados (futuros, pasados, próximos) - dates in 2025/2026 and earlier
-- Future popular events
INSERT INTO EVENTO (ID, TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES (100, 'Concierto Electro', '2025-12-01 20:00:00', 'DJ X', 'Calle Mayor 10', 'Noche de electrónica', 200, TRUE, 18, 50.0, 80.0, 5.0, 1);
INSERT INTO EVENTO (ID, TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES (101, 'Teatro Familiar', '2025-12-15 18:00:00', 'Compania Y', 'Plaza Norte 5', 'Obra para toda la familia', 150, TRUE, 0, 40.0, 70.0, 3.0, 2);
INSERT INTO EVENTO (ID, TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES (102, 'Jazz Night', '2025-12-05 21:00:00', 'Jazz Trio', 'Auditorio Central', 'Tarde de jazz relajado', 80, TRUE, 0, 30.0, 60.0, 4.0, 3);
INSERT INTO EVENTO (ID, TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES (103, 'Pop Evening', '2026-01-10 20:30:00', 'Pop Singer', 'Estadio Oeste', 'Concierto pop', 5000, TRUE, 0, 60.0, 120.0, 6.0, 5);

-- Near-future low-capacity event (edge case: small aforo)
INSERT INTO EVENTO (ID, TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES (110, 'Acustico Local', '2025-12-02 19:00:00', 'Cantautor Z', 'Sala Pequeña', 'Concierto acustico intimo', 10, TRUE, 0, 12.0, 20.0, 2.0, 4);

-- Event with only 1 seat left scenario (we'll insert entries later to fill it)
INSERT INTO EVENTO (ID, TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES (900, 'Evento Aforo 3', '2025-12-20 20:00:00', 'Artista Test', 'Calle Test 1', 'Evento para pruebas de aforo', 3, TRUE, 0, 10.0, 20.0, 2.0, 1);

-- Past events
INSERT INTO EVENTO (ID, TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES (200, 'Concierto Pasado A', '2024-06-10 20:00:00', 'Artista A', 'Calle Antigua 1', 'Concierto pasado A', 100, FALSE, 18, 45.0, 75.0, 4.0, 1);
INSERT INTO EVENTO (ID, TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES (201, 'Festival Pasado B', '2023-08-05 18:00:00', 'Banda B', 'Parque Viejo', 'Festival pasado B', 300, FALSE, 0, 30.0, 60.0, 2.5, 2);
INSERT INTO EVENTO (ID, TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES (202, 'Gira 2022', '2022-11-20 21:00:00', 'Cantante C', 'Plaza C', 'Gira 2022', 400, FALSE, 16, 35.0, 65.0, 3.5, 1);

-- Event with zero capacity (edge case)
INSERT INTO EVENTO (ID, TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES (300, 'Evento Sin Aforo', '2025-12-25 20:00:00', 'Artista Zero', 'Direccion 0', 'Evento con aforo 0', 0, FALSE, 0, 0.0, 0.0, 0.0, 8);

-- Event with age restriction 21+
INSERT INTO EVENTO (ID, TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES (400, 'Noche 21+', '2025-12-31 23:00:00', 'DJ Adult', 'Sala VIP', 'Solo 21+', 150, TRUE, 21, 25.0, 45.0, 5.0, 9);

-- Event with null date (edge case) -> allowed if schema permits
INSERT INTO EVENTO (ID, TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES (500, 'Evento Fecha Nula', NULL, 'Artista X', 'Direccion Nula', 'Evento sin fecha', 50, FALSE, 0, 15.0, 30.0, 2.0, 6);

-- Duplicate titles in different locales
INSERT INTO EVENTO (ID, TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES (600, 'Concierto Gira', '2025-12-10 20:00:00', 'Banda X', 'Calle A 1', 'Parada de la gira', 500, TRUE, 0, 55.0, 90.0, 5.0, 5);
INSERT INTO EVENTO (ID, TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES (601, 'Concierto Gira', '2025-12-11 20:00:00', 'Banda X', 'Calle B 2', 'Segunda fecha gira', 120, TRUE, 0, 50.0, 85.0, 4.0, 3);

-- Event with very high price
INSERT INTO EVENTO (ID, TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES (700, 'Concierto VIP Exclusivo', '2026-02-14 20:00:00', 'Star Artist', 'Sala VIP', 'Evento exclusivo', 100, TRUE, 18, 500.0, 1500.0, 50.0, 9);

-- Events with overlapping dates for stress testing
INSERT INTO EVENTO (ID, TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES (800, 'Maraton Musical', '2025-12-05 20:00:00', 'Various', 'Estadio Oeste', 'Varias bandas seguidas', 8000, TRUE, 0, 20.0, 40.0, 5.0, 5);
INSERT INTO EVENTO (ID, TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES (801, 'Maraton Musical - Dia 2', '2025-12-06 20:00:00', 'Various', 'Estadio Oeste', 'Segunda noche', 8000, TRUE, 0, 20.0, 40.0, 5.0, 5);

-- ENTRADAS: algunas compradas por usuarios para distintos eventos
INSERT INTO ENTRADA (ID, TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA, NOMBRE_EVENTO, NOMBRE_USUARIO) VALUES (1001, 'GENERAL', 0, 1, 100, FALSE, 'Concierto Electro', 'Pedro');
INSERT INTO ENTRADA (ID, TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA, NOMBRE_EVENTO, NOMBRE_USUARIO) VALUES (1002, 'VIP', 1, 1, 100, FALSE, 'Concierto Electro', 'Pedro');
INSERT INTO ENTRADA (ID, TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA, NOMBRE_EVENTO, NOMBRE_USUARIO) VALUES (1003, 'GENERAL', 0, 3, 101, FALSE, 'Teatro Familiar', 'Lucia');
INSERT INTO ENTRADA (ID, TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA, NOMBRE_EVENTO, NOMBRE_USUARIO) VALUES (1004, 'GENERAL', 0, 4, 110, FALSE, 'Acustico Local', 'Carlos');

-- Fill some seats for event 900 so only 1 seat remains (aforo 3)
INSERT INTO ENTRADA (ID, TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA, NOMBRE_EVENTO, NOMBRE_USUARIO) VALUES (2001, 'GENERAL', 0, 6, 900, FALSE, 'Evento Aforo 3', 'UsuarioA');
INSERT INTO ENTRADA (ID, TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA, NOMBRE_EVENTO, NOMBRE_USUARIO) VALUES (2002, 'GENERAL', 0, 7, 900, FALSE, 'Evento Aforo 3', 'UsuarioB');

-- COMPRAS (Compra_Entrada) and join table to associate purchase <-> entradas
INSERT INTO Compra_Entrada (ID, FECHA_COMPRA, PRECIO, USUARIO_ID) VALUES (3001, '2025-11-26 12:00:00', 50.0, 1);
INSERT INTO compra_entrada_entardas (compra_entrada_id, entrada_id) VALUES (3001, 1001);
