INSERT INTO USUARIO (NOMBRE, EMAIL, CONTRASENIA, EDAD, TELEFONO, ADMIN, SALDO) VALUES ('Pedro', 'Pedro@Email.com', 'x', 30, '600000000', FALSE, 100.0);
INSERT INTO USUARIO (NOMBRE, EMAIL, CONTRASENIA, EDAD, TELEFONO, ADMIN, SALDO) VALUES ('Admin', 'admin@example.com', 'adminpass', 35, '600000001', TRUE, 1000.0);

-- Ubicaciones
INSERT INTO UBICACION (NOMBRE) VALUES ('Centro');
INSERT INTO UBICACION (NOMBRE) VALUES ('Norte');

-- Locales (asumiendo que UBICACION IDs serán 1 y 2)
INSERT INTO LOCAL (NOMBRE, UBICACION_ID) VALUES ('Sala Azul', 1);
INSERT INTO LOCAL (NOMBRE, UBICACION_ID) VALUES ('Teatro Norte', 2);
INSERT INTO LOCAL (NOMBRE, UBICACION_ID) VALUES ('Auditorio Central', 1);

-- Eventos (asumiendo LOCAL IDs serán 1 y 2)
INSERT INTO EVENTO (TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES ('Concierto Electro', '2025-12-01 20:00:00', 'DJ X', 'Calle Mayor 10', 'Noche de electrónica', 200, TRUE, 18, 50.0, 80.0, 5.0, 1);
INSERT INTO EVENTO (TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES ('Teatro Familiar', '2025-12-15 18:00:00', 'Compañía Y', 'Plaza Norte 5', 'Obra para toda la familia', 150, TRUE, 0, 40.0, 70.0, 3.0, 2);

-- Eventos pasados para pruebas
INSERT INTO EVENTO (TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES ('Concierto Pasado A', '2024-06-10 20:00:00', 'Artista A', 'Calle Antigua 1', 'Concierto pasado A', 100, FALSE, 18, 45.0, 75.0, 4.0, 1);
INSERT INTO EVENTO (TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES ('Festival Pasado B', '2023-08-05 18:00:00', 'Banda B', 'Parque Viejo', 'Festival pasado B', 300, FALSE, 0, 30.0, 60.0, 2.5, 2);
INSERT INTO EVENTO (TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES ('Gira 2022', '2022-11-20 21:00:00', 'Cantante C', 'Plaza C', 'Gira 2022', 400, FALSE, 16, 35.0, 65.0, 3.5, 1);

-- Muchas entradas de ejemplo para Pedro (USUARIO_ID = 1) y algunas para Admin (USUARIO_ID = 2)
-- Entradas para eventos futuros (ya existentes)
INSERT INTO ENTRADA (TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA) VALUES ('GENERAL', 0, 1, 1, FALSE);
INSERT INTO ENTRADA (TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA) VALUES ('VIP', 1, 1, 1, FALSE);
INSERT INTO ENTRADA (TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA) VALUES ('GENERAL', 0, 1, 2, FALSE);
INSERT INTO ENTRADA (TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA) VALUES ('VIP', 2, 1, 2, FALSE);

-- Entradas para eventos pasados
INSERT INTO ENTRADA (TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA) VALUES ('GENERAL', 0, 1, 3, FALSE);
INSERT INTO ENTRADA (TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA) VALUES ('VIP', 1, 1, 4, FALSE);
INSERT INTO ENTRADA (TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA) VALUES ('GENERAL', 0, 1, 5, FALSE);

-- Algunas entradas más dispersas
INSERT INTO ENTRADA (TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA) VALUES ('GENERAL', 0, 2, 1, FALSE);
INSERT INTO ENTRADA (TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA) VALUES ('VIP', 1, 2, 3, FALSE);

-- Añadimos varias entradas adicionales para simular un usuario activo
INSERT INTO ENTRADA (TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA) VALUES ('GENERAL', 0, 1, 1, FALSE);
INSERT INTO ENTRADA (TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA) VALUES ('GENERAL', 0, 1, 2, FALSE);
INSERT INTO ENTRADA (TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA) VALUES ('VIP', 1, 1, 4, FALSE);
INSERT INTO ENTRADA (TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA) VALUES ('GENERAL', 0, 1, 5, FALSE);

-- Evento de prueba con aforo = 3 y dos usuarios que ya han comprado entradas
INSERT INTO EVENTO (ID, TITULO, FECHA, ARTISTA, DIRECCION, DESCRIPCION, AFORO, ESTADO, EDADPERMITIDA, PRECIO_GENERAL, PRECIO_VIP, PRECIO_CONSUMICION, LOCAL_ID) VALUES (900, 'Evento Aforo 3', '2025-12-20 20:00:00', 'Artista Test', 'Calle Test 1', 'Evento para pruebas de aforo', 3, TRUE, 0, 10.0, 20.0, 2.0, 1);

-- Usuarios de prueba
INSERT INTO USUARIO (ID, NOMBRE, EMAIL, CONTRASENIA, EDAD, TELEFONO, ADMIN, SALDO) VALUES (200, 'UsuarioA', 'usera@example.com', 'pass', 28, '600000100', FALSE, 50.0);
INSERT INTO USUARIO (ID, NOMBRE, EMAIL, CONTRASENIA, EDAD, TELEFONO, ADMIN, SALDO) VALUES (201, 'UsuarioB', 'userb@example.com', 'pass', 30, '600000101', FALSE, 50.0);

-- Entradas ya compradas para el evento (ids explicitos para evitar colisiones)
INSERT INTO ENTRADA (ID, TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA, NOMBRE_EVENTO, NOMBRE_USUARIO) VALUES (2001, 'GENERAL', 0, 200, 900, FALSE, 'Evento Aforo 3', 'UsuarioA');
INSERT INTO ENTRADA (ID, TIPO, CANTIDAD_CONSUMICIONES, USUARIO_ID, EVENTO_ID, DEVUELTA, NOMBRE_EVENTO, NOMBRE_USUARIO) VALUES (2002, 'GENERAL', 0, 201, 900, FALSE, 'Evento Aforo 3', 'UsuarioB');

-- Compras asociadas (con ids explícitos) y join table para relacionar compra <-> entradas
INSERT INTO Compra_Entrada (ID, FECHA_COMPRA, PRECIO, USUARIO_ID) VALUES (3001, '2025-11-26 12:00:00', 10.0, 200);
INSERT INTO compra_entrada_entardas (compra_entrada_id, entrada_id) VALUES (3001, 2001);

INSERT INTO Compra_Entrada (ID, FECHA_COMPRA, PRECIO, USUARIO_ID) VALUES (3002, '2025-11-26 12:10:00', 10.0, 201);
INSERT INTO compra_entrada_entardas (compra_entrada_id, entrada_id) VALUES (3002, 2002);

-- Con esto el evento 900 tendrá 2 entradas ocupadas (aforo 3) y quedará 1 plaza libre
